### PR TITLE
Add event color

### PR DESCRIPTION
**Pull request by Atalonica**
I think it would be really useful for this library to have the option of choosing the event color (optionally).
Having this option available via a service call in Home Assistant would be awesome since all events created get the default color.

### CODE REVIEW

**Review by allenporter — CHANGES_REQUESTED** [review]
I'm supportive of exposing colors.

But does this work? My impression is this is not the correct field name -- it's color id -- and then you also have to fetch the colors from the colors API.

**Comment by allenporter** [comment]
Also since you mentioned Home Assistant: if you end up wanting to add this to home assistant you'll need to actually have an architecture proposal for how this will work, taking into some of the considerations discussed in https://github.com/home-assistant/architecture/discussions/883

**Comment by allenporter** [comment]
My impression is that this still won't work without fetching colors from the API as well. Marking as draft for now until this is ready for review.

**Comment by Atalonica** [comment]
Hello, if there is no enough interest by other people for this feature to be added, this can be closed as I don't have the knowledge to develop on this. Thanks anyway.

**Comment by allenporter** [comment]
Closing based on your comment.

**Pull request closed without merging**
